### ISSUE TITLE
Wrong output code

### ISSUE THREAD

**Issue by phideas** [Sommerregen/grav-plugin-jscomments#15]
If using Gantry plugin, all variables are auto-escaped for security reason. Using {{ jscomments()|raw }} makes it easy to render output correctly. But translations are escaped even after this step and results in wrong output.

Please consider adding `|raw` after translations and make this plugin update proof for Gantry users.
`'PLUGINS.JS_COMMENTS.PROVIDERS.DISQUS.NOSCRIPT'|t|raw`

**Comment by Sommerregen** [comment]
Hi @phideas ,

To be honest I don't use Gantry. However I have added the `raw` filter in the develop branch. You may check it out, if you want. I will release a new version in the next days.

**Comment by phideas** [comment]
Very nice. Now it is "plug&play" and "update proof" for Gantry users too. Gantry is very advanced and popular plugin for Grav. I am sure many users will appreciate this patch. Thank you!

**Comment by Sommerregen** [comment]
Ok, I released a new version today. Have fun 🎉
