### ISSUE TITLE
[JSComments] Facebook comments bloc doesn't appear on the page

### ISSUE THREAD

**Issue by Legend23** [Sommerregen/grav-plugin-jscomments#16]
Hello, 
I'm using Grav v1.1.17 - Admin v1.2.14. 

On the Admin interface I set this setup: 

![image](https://cloud.githubusercontent.com/assets/3600281/24153075/c145cfc6-0e4d-11e7-99a6-e01f09b88ae3.png)

I put my Facebook API key:
![image](https://cloud.githubusercontent.com/assets/3600281/24153131/e3339a8c-0e4d-11e7-82fc-b347fd0ab391.png)

I didn't forget to put this lines in my code:
`{% if config.plugins.jscomments.enabled %}
  {{ jscomments()|raw }}
{% endif %}` 

And when i'm going to the pages where the comments should be with the facebook plugin i don't have anything:

![image](https://cloud.githubusercontent.com/assets/3600281/24153265/3e151f70-0e4e-11e7-9bbf-c9ec77949015.png)

But when i'm changing it for disqus there is the plugin activated:
![image](https://cloud.githubusercontent.com/assets/3600281/24153330/5e031b8e-0e4e-11e7-8721-1934c18bb64c.png)

I don't know where is the problem. 

Thank you very much.

**Comment by Sommerregen** [comment]
Dear @Legend23 ,

I tried it on my local machine, see result here:

![facebook](https://cloud.githubusercontent.com/assets/9073307/24268959/d0ecabca-100f-11e7-8226-707cb0e3d3cf.png)

The horrible thing, I cannot reproduce your issue. First, you may change your language. It must be `fr_FR`. Otherwise it seems there is no dark theme. You can try to use the light theme. I don't know how to help you otherwise. Is the site online. If yes can you point me to it, so that I can inspect it?

**Comment by Legend23** [comment]
Hello @Sommerregen !
First of all, thank you for helping me. 

I tried all the tips you gave me and I have the same problem. 
Here is one link to my website: [https://yoannlaborde.re/blog/departure](url)
By inpecting the code on the page through Chrome, I can see that the module is here, but doesn't appear.

**Comment by Sommerregen** [comment]
@Legend23 Did you solved the issue? When looking at your site I get this:

![screenshot](https://cloud.githubusercontent.com/assets/9073307/24326007/3b882efa-11a5-11e7-8eab-b4cfdc9f0eb7.png)

I'm using **Firefox 50.1**. Might be a chrome issue or maybe JavaScript that is blocked.

**Comment by Legend23** [comment]
@Sommerregen It's really weird. I tried it with newest version of chrome and firefox, seems to be blocked only with my laptop. 

I tried with another devices, and **it works well.** 

Sorry for this trouble. 
We can close this ticket.
