### ISSUE TITLE
Not showing up

### ISSUE THREAD

**Issue by starik1968** [Sommerregen/grav-plugin-jscomments#20]
I installed latest JSComments ins Grav. Enabled it. Did not show up on page. Only if I put the code in my twigfile ({{ jscomments('disqus', { shortname: '-------' }) }} it works. But than on all my pages processed with this twigfile. What can I do? Or what do I wrong? Read the readme.md but have no clue what to do.

**Comment by Sommerregen** [comment]
Hi @starik1968 ,

First, they are two options: `enabled` and `active`. Please make sure that both are set to **true**. Second, you need to set a provider [jscomments.yaml#L8](https://github.com/Sommerregen/grav-plugin-jscomments/blob/develop/jscomments.yaml#L8). Third, you need to configure [jscomments.yaml#L16-L19](https://github.com/Sommerregen/grav-plugin-jscomments/blob/develop/jscomments.yaml#L16-L19). All can be done from Admin interface.

**Comment by starik1968** [comment]
my user/config/plugins/jscomments.yaml (shortname not shown here)

```yaml
enabled: true
active: true
provider: disqus
providers:
  disqus:
    shortname: XXXXXXX
    show_count: true
    language: de
```

If I set in user/themes/mytheme/templates/partials|blog_item.html.twig

```twig
</div>
    {{ jscomments('disqus', { shortname: 'XXXXXXXXXXXX' }) }}
</div>
```

comments shows up, but on every post, but I want set for every site differently

**Comment by Sommerregen** [comment]
Hi @starik1968 ,

your configuration setting seems fine. btw: you don't have to use `{{ jscomments('disqus', { shortname: 'XXXXXXXXXXXX' }) }}`,

```twig
{{ jscomments()|raw }}
```

with the above settings is enough.

I hope I understand you right, to interpret site with "page". If yes, you can set your settings directly in the page header

```yaml
jscomments:
  provider: 'disqus' # or whatever
``` 

with the same options as the plugin has. But setting a provider here is enough. The page headers configuration will be automatically merged with the plugin settings. You can further change the comment provider for a collection of pages. Just add the above snippet in the page header of any page collection or parent of pages. For antimatter for example, inserting it in `blog.md` means, very `blog_item.md` will have disqus comments. That's an undocumented feature, but it might be the one you are looking for.

**Comment by Sommerregen** [comment]
Closed due to inactivity. Feel free to reopen if the issue still persists.
