### ISSUE TITLE
ssl for intensedebate

### ISSUE THREAD

**Issue by dmayo2** [Sommerregen/grav-plugin-jscomments#21]
In `user/plugins/jscomments/templates/plugins/jscomments/intensedebate.html.twig` line 14 there is a call to a remote JS file: `http://www.intensedebate.com/js/genericCommentWrapperV2.js`

Since my GRAV site is running full HTTPS, jscomments is failing.

Might want to delete the protocol:

`<script src="//www.intensedebate.com/js/genericCommentWrapperV2.js"></script>`

**Comment by Sommerregen** [comment]
Good, point. Published a new release!
