### ISSUE TITLE
Issue with HyperComments : No login solution except anonymous

### ISSUE THREAD

**Issue by foufrix** [Sommerregen/grav-plugin-jscomments#23]
Hi, first thank you for the plugin, i tried with disqs and it works smoothly, but disqus slow down the site too much.

I tried all but my attention stayed on hypercomments (why it is not so famous because it's a supernice one !)

The integration works perfectly, the only problem i have is that i have no social media option to log in to post a comment, only anonymous. I've put only facebook and google to be sure it was not another problem on the social media order in the plugin option, but still nothing.

I've also searched on hypercomments dashboard but nothing either (i have not done any tweaking on the dashboard, maybe it's from there but can't find a solution on my own)

Thanks in advance for the help !

**Comment by Sommerregen** [comment]
Hi @foufrix ,

And thanks for using my plugin!

First of all, have you tried one of other social networks as described in the documentation (https://www.hypercomments.com/en/documentation, key: `social`)? Second, can you double check in your browser, that everything is loaded fine? Your page must have a `<div id="jscomments">` tag somewhere. There you can also find the important setting in the javascript tag `_hcwp`. It must contain the social key with your settings. You may also open the developer console and see whether there are any errors preventing you from seeing the social media login.

Unfortunately, I can test this on my own as I don't have a HyperComments at hand.

**Comment by foufrix** [comment]
Thanks for the quick answer,

I did not understand the first part of your message : (https://www.hypercomments.com/en/documentation, key: social) -> key social is the one in Grav jscomments.yaml ? Here is my code :
``` 
hypercomments:
    widget_id: 12345
    social:
      - google
      - facebook
```

and for the second part here is the code of my page on the html 


```
<div id="jscomments">
  <div id="hypercomments_widget"></div>
    
  <script type="text/javascript">
  _hcwp = window._hcwp \|\| [];
  _hcwp.push({
  widget: "Stream",
  widget_id: '99899',
  social: 'Array'
});
```

maybe it's the social: 'Array' the problem ?

UPDATE : 
I just tried to change the value in my twig template, i put : 

`{{ jscomments('hypercomments', { 'widget_id': 12345, 'social': facebook })|raw }}`

now i have all social media available, i only want to put facebook, google and twitter

SOLUTION : 

Problem found ! yeahh !

if i put : 
`{{ jscomments('hypercomments', { 'widget_id': 12345, 'social': 'facebook,google' })|raw }}`

it's working

but if i put 
`{{ jscomments()|raw }}`

It does not take the parameter from the jscomments.yaml, so i think that there is a small problem and it's not in String in the jscomments plugin, i have no idea where to look but i'm gonna try and push it if i found it

UPDATE 2 : 
in the plugin file in hypercomments template l 19 : 
`social: '{{ social|e('js') }}'`

Social here is an array where it should be a String like this : 
`social: '{{ social|join(',') }}'`

**Comment by Sommerregen** [comment]
That's a very good catch! Haven't thought about this very carefully. Thanks for finding it 👍
