### ISSUE TITLE
Beta Grav and Admin issues with translating Discourse Title tab

### ISSUE THREAD

**Issue by JohnMica** [Sommerregen/grav-plugin-jscomments#4]
Hi there,

It sems that the translation of the filed Discourse in the new version is not beeing picked up on the latest beta version of Grav and Admin as per the pciture attached.

Just wanted to let you know maybe in the next version it will be fixed.

![captura de ecran din 2016 05 14 la 14 54 54](https://cloud.githubusercontent.com/assets/7076631/15268346/0ec92716-19e4-11e6-9145-1799edaf3a8c.png)

**Comment by Sommerregen** [comment]
Hi @JohnMica ,

thank you for notifying me of the bug! I just noticed that an English translation string was missing. There were further typos and bugs in the code, which I fixed in **v2.0.0-beta.2** (released now).
