### ISSUE TITLE
Uncaught Error: invalid version specified

### ISSUE THREAD

**Issue by Perlkonig** [Sommerregen/grav-plugin-jscomments#9]
I'm trying to use the `facebook` provider. I've entered my `app_id` and added `{{ jscomments() }}` to my twig. But nothing appears, and in the console I see `Uncaught Error: invalid version specified` at `sdk.js:99`. Any ideas? Thanks!

**Comment by Sommerregen** [comment]
Thanks for the issue and your fix :+1:
